import { readdir, readFile, writeFile } from "fs/promises";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const envDir = join(__dirname, "..");

async function generateServerEnvMap() {
  // Find all server env files (excluding defaults and generated files)
  const files = await readdir(envDir);
  const serverEnvFiles = files.filter(
    (file) => file.endsWith("-env.server.ts") && !file.includes(".defaults.") && !file.includes("all-server-env")
  );

  // Parse each file to find the actual export name
  const envModules: { file: string; exportName: string }[] = [];

  for (const file of serverEnvFiles) {
    const content = await readFile(join(envDir, file), "utf-8");
    // Look for export { someEnv };
    const exportMatch = content.match(/export\s*{\s*([\w]+)\s*}/);
    if (exportMatch) {
      envModules.push({
        file: file.replace(".ts", ""),
        exportName: exportMatch[1],
      });
    }
  }

  // Sort for consistent output
  envModules.sort((a, b) => a.file.localeCompare(b.file));

  // Generate imports
  const imports = envModules
    .map(({ file, exportName }) => {
      return `import { ${exportName} } from "./${file}";`;
    })
    .join("\n");

  // Generate the consolidated env object entries
  const envEntries = envModules
    .map(({ exportName }) => {
      return `    ...${exportName},`;
    })
    .join("\n");

  // Generate exports
  const exports = envModules
    .map(({ exportName }) => {
      return `  ${exportName},`;
    })
    .join("\n");

  const content = `//
//
// ⚠️ AUTO-GENERATED — DO NOT EDIT
//
// 

/**
 * Consolidated server environment that merges all service-specific environments
 * 
 * This file is auto-generated by env-map.generate.ts
 */

${imports}

/**
 * Extract public environment variables from all sources
 * 
 * Public env vars are those that start with PUBLIC_
 */
export const getAllPublicEnv = () => {
  const allEnvs = {
${envEntries}
  };
  
  // Filter only PUBLIC_ prefixed variables
  return Object.fromEntries(
    Object.entries(allEnvs).filter(([key]) => key.startsWith("PUBLIC_"))
  );
};

/**
 * Export all server environments for easy access
 */
export {
${exports}
};`;

  // Write the generated file
  const outputPath = join(envDir, "all-server-env.ts");
  await writeFile(outputPath, content);

  console.log(`✓ Generated server env map with ${envModules.length} env files`);
}

async function generateClientEnvMap() {
  // Find all client env files
  const files = await readdir(envDir);
  const allClientEnvFiles = files.filter((file) => file.endsWith(".client.ts") && !file.includes("all-client-env"));

  // Separate defaults from regular files
  const defaultFiles = allClientEnvFiles.filter((f) => f.includes(".defaults."));
  const regularFiles = allClientEnvFiles.filter((f) => !f.includes(".defaults."));

  // Parse each file to extract window.env interface properties and export names
  const envVars = new Map<string, string>(); // var name -> description
  const envModules: { file: string; exportName: string }[] = [];

  // Process all files for env var extraction
  for (const file of allClientEnvFiles) {
    const content = await readFile(join(envDir, file), "utf-8");

    // Look for @env comments
    const envCommentMatches = content.matchAll(/@env\s+(PUBLIC_[A-Z_]+)\s*-\s*(.+)/g);
    for (const match of envCommentMatches) {
      const varName = match[1];
      const description = match[2];
      envVars.set(varName, description);
    }

    // Also look for direct references to window.env properties
    const windowEnvMatches = content.matchAll(/window\.env\??\.(PUBLIC_[A-Z_]+)/g);
    for (const match of windowEnvMatches) {
      const varName = match[1];
      if (!envVars.has(varName)) {
        envVars.set(varName, "");
      }
    }

    // Look for existing interface definitions (for backwards compatibility)
    const interfaceMatches = content.matchAll(/interface\s+Window\s*{[^}]*env\s*:\s*{([^}]*)}/gs);
    for (const match of interfaceMatches) {
      const interfaceContent = match[1];
      const propMatches = interfaceContent.matchAll(/(PUBLIC_[A-Z_]+)\s*\?\s*:\s*([^;]+);/g);
      for (const propMatch of propMatches) {
        const varName = propMatch[1];
        if (!envVars.has(varName)) {
          envVars.set(varName, "");
        }
      }
    }

    // Only add exports for non-default files
    if (!file.includes(".defaults.")) {
      const exportMatch = content.match(/export\s*{\s*([\w]+)\s*}/);
      if (exportMatch) {
        envModules.push({
          file: file.replace(".ts", ""),
          exportName: exportMatch[1],
        });
      }
    }
  }

  // Sort for consistent output
  envModules.sort((a, b) => a.file.localeCompare(b.file));

  // Generate imports
  const imports = envModules
    .map(({ file, exportName }) => {
      return `import { ${exportName} } from "./${file}";`;
    })
    .join("\n");

  // Generate interface properties
  const interfaceProperties: string[] = [];
  for (const [varName, description] of envVars) {
    if (description) {
      interfaceProperties.push(`      // ${description}`);
    }
    interfaceProperties.push(`      ${varName}?: string;`);
  }

  // Generate exports
  const exports = envModules.map(({ exportName }) => `  ${exportName},`).join("\n");

  const content = `//
//
// ⚠️ AUTO-GENERATED — DO NOT EDIT
//
// 

/**
 * Consolidated client environment type declarations
 * 
 * This file is auto-generated by env-map.generate.ts
 */

${imports}

declare global {
  interface Window {
    env: {
${interfaceProperties.join("\n")}
    };
  }
}

/**
 * Export all client environments for easy access
 */
export {
${exports}
};`;

  // Write the generated file
  const outputPath = join(envDir, "all-client-env.ts");
  await writeFile(outputPath, content);

  console.log(
    `✓ Generated client env map with ${regularFiles.length} env files (${envVars.size} env vars from ${allClientEnvFiles.length} total files)`
  );
}

// Run all generators
await generateServerEnvMap();
await generateClientEnvMap();
