//
//
// ⚠️ AUTO-GENERATED — DO NOT EDIT
//
//

/**
 * Consolidated server environment that merges all service-specific environments
 *
 * This file is auto-generated by env-map.generate.ts
 */

import { coreEnv } from "./core-env.server";
import { paddleEnv } from "./paddle-env.server";

/**
 * Extract public environment variables from all sources
 *
 * Public env vars are those that start with PUBLIC_
 */
export const getAllPublicEnv = () => {
  const allEnvs = {
    ...coreEnv,
    ...paddleEnv,
  };

  // Filter only PUBLIC_ prefixed variables
  return Object.fromEntries(
    Object.entries(allEnvs).filter(([key]) => key.startsWith("PUBLIC_"))
  );
};

/**
 * Export all server environments for easy access
 */
export {
  coreEnv,
  paddleEnv,
};