//
//
// ⚠️ AUTO-GENERATED — DO NOT EDIT
//
//

/**
 * Consolidated client environment type declarations
 *
 * This file is auto-generated by env-map.generate.ts
 */



declare global {
  interface Window {
    env: {
      // Paddle client-side token (public by design; sandbox/live differ)
      PUBLIC_PADDLE_CLIENT_TOKEN?: string;
      // Paddle JS environment ("sandbox" | "production")
      PUBLIC_PADDLE_ENVIRONMENT?: string;
    };
  }
}

/**
 * Export all client environments for easy access
 */
export {

};