// This file is generated automatically by scripts/generate-routes.ts
// Do not edit this file directly.
// To regenerate this file, run:
//   task generate-routes
//
import { components, hooks, utils } from "~/lib/router/generouted-components";

// all paths get defined here...
export const routePaths = [
  "/",
  "/:lang",
  "/:lang/about",
  "/:lang/checkout",
  "/:lang/contact",
  "/:lang/download",
  "/:lang/faq",
  "/:lang/help",
  "/:lang/how-it-works",
  "/:lang/pricing",
  "/:lang/privacy",
  "/:lang/refunds",
  "/:lang/source",
  "/:lang/terms",
  "/about",
  "/checkout",
  "/contact",
  "/download",
  "/download[/]dmg",
  "/faq",
  "/help",
  "/how-it-works",
  "/pricing",
  "/privacy",
  "/refunds",
  "/source",
  "/terms",
] as const;
export type Path = (typeof routePaths)[number];

// all params for any given path get defined here...
export type Params = {
  "/:lang": { lang: string };
  "/:lang/about": { lang: string };
  "/:lang/checkout": { lang: string };
  "/:lang/contact": { lang: string };
  "/:lang/download": { lang: string };
  "/:lang/faq": { lang: string };
  "/:lang/help": { lang: string };
  "/:lang/how-it-works": { lang: string };
  "/:lang/pricing": { lang: string };
  "/:lang/privacy": { lang: string };
  "/:lang/refunds": { lang: string };
  "/:lang/source": { lang: string };
  "/:lang/terms": { lang: string };
};

// Utility type to extract the leaf nodes of Params
type LeafNodes<T> = T[keyof T];

// Merge all leaf nodes into one big object type
type MergeLeafNodes<T> = UnionToIntersection<LeafNodes<T>>;

// Utility type to convert a union type to an intersection type
type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I,
) => void
  ? I
  : never;

// Combined type of all the leaf nodes
export type AllParams = MergeLeafNodes<Params>;

export const { Link, NavLink } = components<Path, Params>();
export const { useNavigate, useParams } = hooks<Path, Params>();
export const { redirect, generatePath } = utils<Path, Params>();
